name: 🐛 Bug Report
description: Report a bug or issue
title: "[BUG] "
labels: ["type: bug", "stage: refinement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide details to help us fix it.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Clear description of the bug
      placeholder: "Letters don't fall on mobile devices..."
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen?
      placeholder: "Letters should fall at normal speed..."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens?
      placeholder: "Letters fall very slowly or not at all..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Open game on iPhone
        2. Click PLAY
        3. Observe letter fall speed
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: dropdown
    id: game
    attributes:
      label: Affected Game/Area
      description: Where does this bug occur?
      options:
        - ABC Learning
        - Game Launcher
        - All games
        - Documentation
        - Tests
        - Other (specify below)
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser
      description: Which browser?
      placeholder: "Chrome 120, Safari 17, etc."
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: Device
      description: Which device?
      placeholder: "iPhone 14, Desktop Windows 11, etc."
    validations:
      required: true

  - type: dropdown
    id: frequency
    attributes:
      label: Frequency
      description: How often does this happen?
      options:
        - Always (100%)
        - Often (75%)
        - Sometimes (50%)
        - Rarely (25%)
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How bad is this bug?
      options:
        - 🔴 Critical - Game is unplayable
        - 🟠 Major - Significant functionality broken
        - 🟡 Minor - Small issue, workaround exists
        - 🟢 Trivial - Cosmetic issue
      default: 2

  - type: textarea
    id: console-errors
    attributes:
      label: Console Errors
      description: Any errors in browser console? (F12)
      placeholder: "Paste console errors here..."
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Add screenshots if helpful

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Anything else we should know?
