name: 📚 Documentation
description: Improve or add documentation
title: "[DOCS] "
labels: ["type: docs", "stage: ideation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation!

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What kind of documentation?
      options:
        - New documentation
        - Update existing docs
        - Fix typo/error
        - Add examples
        - Improve clarity
        - Translation
      multiple: true
    validations:
      required: true

  - type: input
    id: file
    attributes:
      label: File(s) Affected
      description: Which documentation files?
      placeholder: "docs/development.md, README.md, etc."

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What needs to be documented or improved?
      placeholder: "The setup instructions are unclear..."
    validations:
      required: true

  - type: textarea
    id: proposed-changes
    attributes:
      label: Proposed Changes
      description: What should be changed or added?
      placeholder: "Add step-by-step screenshots for setup..."

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this?
      options:
        - 🔴 High - Critical missing docs
        - 🟡 Medium - Nice to have
        - 🟢 Low - Minor improvement
      default: 1

  - type: textarea
    id: audience
    attributes:
      label: Target Audience
      description: Who is this documentation for?
      placeholder: "New contributors, AI assistants, end users, etc."

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Examples, references, or screenshots
